// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-m_oje4Op55JEq0tgLsSM5Bno4vEAAo',
    appId: '1:515532083039:web:4f236532a42393ef6fb0ea',
    messagingSenderId: '515532083039',
    projectId: 'popovd-mis-lab-3',
    authDomain: 'popovd-mis-lab-3.firebaseapp.com',
    storageBucket: 'popovd-mis-lab-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXrFo2k0EiJIQCBw4vbG_m4MxEsjJj_h0',
    appId: '1:515532083039:android:7865d34a051835686fb0ea',
    messagingSenderId: '515532083039',
    projectId: 'popovd-mis-lab-3',
    storageBucket: 'popovd-mis-lab-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwrDlpLqUL-8UzAxsnT6kVe1UFiIm-2c',
    appId: '1:515532083039:ios:8b5751800d040fe36fb0ea',
    messagingSenderId: '515532083039',
    projectId: 'popovd-mis-lab-3',
    storageBucket: 'popovd-mis-lab-3.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwrDlpLqUL-8UzAxsnT6kVe1UFiIm-2c',
    appId: '1:515532083039:ios:8b5751800d040fe36fb0ea',
    messagingSenderId: '515532083039',
    projectId: 'popovd-mis-lab-3',
    storageBucket: 'popovd-mis-lab-3.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK-m_oje4Op55JEq0tgLsSM5Bno4vEAAo',
    appId: '1:515532083039:web:80e26e7f236f9eae6fb0ea',
    messagingSenderId: '515532083039',
    projectId: 'popovd-mis-lab-3',
    authDomain: 'popovd-mis-lab-3.firebaseapp.com',
    storageBucket: 'popovd-mis-lab-3.firebasestorage.app',
  );

}